spring.application.name=s3lab

# MULTIPART
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# S3
s3.endpoint=http://localhost:9000
s3.region=ap-northeast-2
s3.bucket=s3-lab-bucket
s3.access-key=minioadmin
s3.secret-key=minioadmin123

# FILE EXPIRE
# 현재는 학습중이라 만료시간 10초, job실행 주기도 10초
file.pending-expiration-seconds=10
file.expire-schedule-ms=10000


