spring.application.name=s3lab

# MULTIPART
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# S3
s3.endpoint=http://localhost:9000
s3.region=ap-northeast-2
s3.bucket=s3-lab-bucket
s3.access-key=minioadmin
s3.secret-key=minioadmin123

# FILE EXPIRE
# 현재는 학습중이라 만료시간 10초, job실행 주기도 10초
file.pending-expiration-seconds=10
file.expire-schedule-ms=10000

# logging
# 우리 서버 로그는 DEBUG 이상 출력
# AWS SDK 내부 로그는 WARN 이상만 출력
logging.level.com.example.s3lab=DEBUG
logging.level.software.amazon.awssdk=WARN
